basePath: /api
definitions:
  handlers.HTTPError:
    properties:
      message:
        example: bad request
        type: string
      status:
        example: 400
        type: integer
    type: object
  model.Scholar:
    properties:
      nama:
        type: string
      nim:
        type: integer
      semester:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /mahasiswa/{id}:
    get:
      consumes:
      - application/json
      description: mengambil data berdasarkan NIM
      parameters:
      - description: NIM
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Scholar'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.HTTPError'
      summary: menampilkan data mahasiswa
      tags:
      - mahasiswa
swagger: "2.0"
